owner: sonyakun
repo: bc-status

sites:
  - name: FriendConnect
    url: http://bcstat.sonyakun.com:50212

status-website:
  baseUrl: /bc-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: sHFI status
  introTitle: 
  introMessage: 
