owner: sonyakun
repo: bc-status

sites:
  - name: BedrockConnect
    url: http://bcstat.sonyakun.com:50212

status-website:
  baseUrl: /bc-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: sonyakun-Hosted FriendConnect Instance status
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
